apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  annotations:
    backstage.io/kubernetes-id: idp-openstack
  name: devportal-root
  description: DevPortal Root Location
spec:
  targets:
    - ./templates/microservice/template.yaml
    - ./templates/namespace/template.yaml
    - ./templates/postgresql/template.yaml
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/kubernetes-id: idp-openstack
  name: idp-openstack
  description: Internal Developer Platform on OpenStack - Backstage, ArgoCD, Crossplane, Vault, Kyverno, Calico
  tags:
    - backstage
    - openstack
    - kubernetes
    - platform
spec:
  type: service
  lifecycle: production
  owner: platform-engineers
  system: devportal-platform
