apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform-engineers
  description: Platform Engineering Team
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: devportal-platform
  description: DevPortal Internal Developer Platform
  tags:
    - platform
    - openstack
spec:
  owner: platform-engineers
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: abderraouf
spec:
  profile:
    displayName: Abderraouf
    email: abderraouf.zek@gmail.com
  memberOf: [platform-engineers]
