backstage:
  appConfig:
    app:
      baseUrl: https://devportal.197.140.32.144.sslip.io
      extensions:
      - page:catalog:
          config:
            path: /
      title: DevPortal
    auth:
      environment: development
      providers:
        guest:
          dangerouslyAllowOutsideDevelopment: true
    backend:
      baseUrl: https://devportal.197.140.32.144.sslip.io
      cors:
        credentials: true
        methods:
        - GET
        - HEAD
        - PATCH
        - POST
        - PUT
        - DELETE
        origin: https://devportal.197.140.32.144.sslip.io
      csp:
        connect-src:
        - '''self'''
        - 'http:'
        - 'https:'
      database:
        client: pg
        connection:
          host: ${POSTGRES_HOST}
          password: ${POSTGRES_PASSWORD}
          port: ${POSTGRES_PORT}
          user: ${POSTGRES_USER}
      https:
        certificate:
          cert:
            $file: /etc/backstage/tls/tls.crt
          key:
            $file: /etc/backstage/tls/tls.key
      listen:
        port: 7007
    catalog:
      providers:
        github:
          devportalLabs:
            catalogPath: /catalog-info.yaml
            filters:
              branch: main
              repository: .*
            organization: devportal-labs
            schedule:
              frequency:
                minutes: 5
              timeout:
                minutes: 3
        githubOrg:
          githubUrl: https://github.com/devportal-labs
          id: devportalLabsOrg
          schedule:
            frequency:
              minutes: 10
            timeout:
              minutes: 3
      rules:
      - allow:
        - Component
        - System
        - API
        - Resource
        - Location
        - User
        - Group
        - Template
    integrations:
      github:
      - host: github.com
        token: ${GITHUB_TOKEN}
    notifications:
      enabled: false
    organization:
      name: DevPortal
    permission:
      enabled: false
  extraEnvVars:
  - name: POSTGRES_HOST
    value: devportal-postgresql
  - name: POSTGRES_PORT
    value: '5432'
  - name: POSTGRES_USER
    value: backstage
  - name: NODE_TLS_REJECT_UNAUTHORIZED
    value: '0'
  extraEnvVarsSecrets:
  - backstage-secrets
  extraVolumeMounts:
  - mountPath: /etc/backstage/tls
    name: tls-certs
    readOnly: true
  extraVolumes:
  - name: tls-certs
    secret:
      secretName: backstage-tls-secret
  image:
    registry: ghcr.io
    repository: abderraoufzekkour/devportal
    tag: 1.0.5
  livenessProbe:
    httpGet:
      path: /.backstage/health/v1/liveness
      port: 7007
      scheme: HTTPS
  readinessProbe:
    httpGet:
      path: /.backstage/health/v1/readiness
      port: 7007
      scheme: HTTPS
  service:
    nodePorts:
      backend: 30443
    ports:
      backend: 7007
      name: tls-backend
      targetPort: backend
    type: NodePort
  startupProbe:
    httpGet:
      path: /.backstage/health/v1/liveness
      port: 7007
      scheme: HTTPS
ingress:
  enabled: false
postgresql:
  auth:
    database: backstage
    password: Backstage2026
    username: backstage
  enabled: true
service:
  nodePorts:
    backend: 30443
  ports:
    backend: 7007
    name: tls-backend
    targetPort: backend
  type: NodePort
nodeSelector:
  kubernetes.io/hostname: p1-worker2
